# Overview {.unnumbered}

## Aim and Learning Objectives

This sub-module aims to provide training and skills on a set of basic quantitative research methods for data collection, analysis, and interpretation. You will learn how to define coherent, relevant research questions, utilise various research quantitative methods, and identify appropriate methodologies to tackle your research questions. **This block serves as the foundation for the dissertation and fieldwork modules.**

**Background**

Data and research are key pillars of the global economy and society today. We need rigorous approaches to collecting and analysing both the statistics that can tell us ‘how much’ and if there are observable relationships between phenomena; and the information gives us a nuanced understanding of cultural contexts and human dynamics. Quantitative skills enable us to explore and measure socio-economic activities and processes at large scales, while qualitative skills enable understanding of social, cultural, and political contexts and diverse lived experiences. Rather than being in opposition, qualitative and quantitative research can complement one another in the investigation of today’s pressing research questions.

To these ends, this block will help you develop your quantitative (statistical) skills, as critical tools. This course will help you understand what quantitative statistical researchers use and develop a set of research techniques that can be used in your field classes and dissertations. 

**Learning objectives:**

- Understand how to explore a dataset, containing a number of observations described by a set of variables.
- Demonstrate an understanding in the application and interpretation of commonly used quantitative research methods.
- Demonstrate an understanding of how to work with quantitative data to address real-world research questions.

## Module Structure

**Staff:**
Dr Zi Ye and Dr Gabriele Filomena

**Where and When**

Quantitative Block (Weeks 7-12): 

 - **Lecture**: 10 am – 10.45 am Fridays
 - **PC Practical sessions**: 11am – 1 pm, following the Lecture

**Week 7**: Central Teaching Hub: PC Teaching Centre BLUE+GREEN+ORANGE ZONES

**Week 8 -12**: Central Teaching Hub, PCTC

Lectures will introduce and explain the fundamentals of quantitative methods, with the opportunity to apply the method introduced in the labs later in the week.

The computer practical sessions, will give you the chance to use and apply quantitative methods to real-world data. 
These are primarily self-directed sessions, but with support on hand if you get stuck. Support and training in R will be provided through these sessions. Weekly sessions will be driven by empirical research questions.


| Week | Topic                                       | Format                          | Staff |
|------|---------------------------------------------|---------------------------------|-------|
| 7    | Introduction & Review                       | Lecture and Computer Lab Practical | GF    |
| 8    | Single & Multiple Linear Regression         | Lecture and Computer Lab Practical | GF    |
| 9    | Multiple Linear Regression with Categorical Variables | Lecture and Computer Lab Practical | ZY    |
| 10   | Logistic Regression                         | Lecture and Computer Lab Practical | ZY    |
| 11   | Data Visualisation                          | Lecture and Computer Lab Practical | GF    |
| 12   | Summary and Assessment Support              | Lecture and Computer Lab Practical | ZY    |


## Software and Data

For quantitative training sessions, ensure you have installed and/or have access to **RStudio**. To run the analysis and reproduce the code in R, you need the following software installed on your machine:

- R-4.2.2
- RStudio 2022.12.0-353

To install and update:

 - R, download the appropriate version from [The Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/).
 - RStudio, download the appropriate version from [here](https://posit.co/download/rstudio-desktop/).

**This software is already installed on University Machines. But you will need it to run the analysis on your personal devices.**

**Data**

Example datasets could be accessed through Canvas or the [GitHub](https://github.com/GDSL-UL/stats) Repository of the module. These include:

- 2021 UK Census Data.
- 2021 Annulation Population Survey.
- 2016 Family Resource Survey.

*Note: The Annual Population Survey requires the completion of a form prior to its usage, as it is licensed.*
